# Generated by Django 4.2.20 on 2025-04-27 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArrestData",
            fields=[
                (
                    "arrest_key",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("arrest_date", models.DateField()),
                ("ofns_desc", models.TextField()),
                ("law_cat_cd", models.TextField()),
                ("x_coord_cd", models.IntegerField(blank=True, null=True)),
                ("y_coord_cd", models.IntegerField(blank=True, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("boroname", models.TextField(blank=True, null=True)),
                ("nta2020", models.TextField(blank=True, null=True)),
                ("ntaname", models.TextField(blank=True, null=True)),
                ("cdta2020", models.TextField(blank=True, null=True)),
                ("cdtaname", models.TextField(blank=True, null=True)),
                ("population", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "arrest_data",
                "managed": False,
            },
        ),
    ]
