# Generated by Django 4.2.20 on 2025-03-14 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_username"),
    ]

    operations = [
        migrations.AlterModelManagers(name="customuser", managers=[],),
    ]
