# Generated by Django 4.2.20 on 2025-03-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_emergencycontact"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emergencycontact",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="emergencycontact",
            name="email",
            field=models.EmailField(blank=True, max_length=200, unique=True),
        ),
    ]
