# Generated by Django 4.2.20 on 2025-04-03 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_emergencycontact_phone_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emergencycontact",
            name="email",
        ),
        migrations.AddField(
            model_name="emergencycontact",
            name="phone_number",
            field=models.CharField(default="000-000-0000", max_length=15, unique=True),
        ),
    ]
