# Generated by Django 4.2.20 on 2025-04-03 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_emergencycontact_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emergencycontact",
            name="carrier",
            field=models.CharField(default="Unknown", max_length=25),
        ),
    ]
