# Generated by Django 4.2.20 on 2025-04-18 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_customuser_options_alter_customuser_groups_and_more"),
        ("users", "0007_emergencycontact_carrier"),
    ]

    operations = []
